version: "3"

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
  
services:
    app:
        container_name: hobbifyStats
        build:
            context: .
            dockerfile: ./compose/local/flask/Dockerfile
        depends_on:
            - postgres
        volumes:
            - .:/app
        env_file:
            - ./.env/.local/.flask
            - ./.env/.local/.postgres
        ports:
            - "80:80"
        command: /start

    postgres:
        build:
            context: .
            dockerfile: ./compose/local/postgres/Dockerfile
        image: hobbify_local_postgres
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        env_file:
            - ./.env/.local/.postgres
        

