version: "3"
services:
    app:
        container_name: hobbifyStats
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        ports:
            - "5000:5000"
    
    

