version: "3"

services:
    app:
        container_name: hobbifyStats
        build:
            context: .
            dockerfile: ./compose/production/flask/Dockerfile
        volumes:
            - .:/app
        env_file:
            - ./.env/.production/.flask
            - ./.env/.production/.postgres
        ports:
            - "80:80"
        command: /start